hyper:
    img_size: 128
    batch_size: 32
    nepoch: 1
    lr: 3.0e-3
    wd: 0
    decay_step: 800
    decay_rate: 0.8
    warmup: 400
aug:
    bright: [0.9, 1.1]
    rotate: 10
env:
    log_root: "/root/proj/examples/logbook"
    data_root: "/root/data"
    ngpu: 2
    # training mode
    # sg: single gpu
    # dp: data parallel
    # dt: distributed training
    train_mode: "dp"